import { CoreMenu } from '@core/types'

export const menu: CoreMenu[] = [

  {
    id: "avatars",
    title: "Users",
    translate: "MENU.DASHBOARD.users",
    type: "collapsible",
    icon: "users",
    children: [
      {
        id: "avatars-list",
        title: "List",
        translate: "MENU.DASHBOARD.list",
        type: "item",
        icon: "circle",
        url: "settings/avatars",
      },
      {
        id: "avatars-add",
        title: "Add",
        translate: "MENU.DASHBOARD.add",
        type: "item",
        icon: "circle",
        url: "settings/add-avatar",
      },
    ],
  },
  {
    id: "avatars",
    title: "Avatars",
    translate:  "MENU.DASHBOARD.ads",
    type: "collapsible" ,
    icon: "image", 
    children: [
      {
        id: "avatars-list",
        title: "List",
        translate: "MENU.DASHBOARD.list",
        type: "item",
        icon: "circle",
        url: "ads",
      },
      {
        id: "avatars-add",
        title: "Add",
        translate: "MENU.DASHBOARD.add",
        type: "item",
        icon: "circle",
        url: "add-ads",
      },
    ],
  },
  {
    id: "avatars",
    title: "Avatars",
    translate:  "MENU.DASHBOARD.counselors",
    type: "collapsible",
    icon: "image",
    children: [
      {
        id: "avatars-list",
        title: "List",
        translate: "Stores",
        type: "item",
        icon: "circle",
        url: "counselors",
      },
      {
        id: "avatars-add",
        title: "Add",
        translate: "MENU.DASHBOARD.add",
        type: "item",
        icon: "circle",
        url: "add-counselors",
      },
    ],
  },
  {
    id: "avatars",
    title: "Avatars",
    translate:  "MENU.DASHBOARD.stores_offers",
    type: "collapsible",
    icon: "image",
    children: [
      {
        id: "avatars-list",
        title: "List",
        translate: "Vouchers",
        type: "item",
        icon: "circle",
        url: "settings/avatars",
      },
      {
        id: "avatars-add",
        title: "Add",
        translate: "MENU.DASHBOARD.add",
        type: "item",
        icon: "circle",
        url: "settings/add-avatar",
      },
    ],
  },
  {
    id: "avatars",
    title: "Avatars",
    translate:  "MENU.DASHBOARD.cancelation_reason",
    type: "collapsible",
    icon: "image",
    children: [
      {
        id: "avatars-list",
        title: "List",
        translate: "MENU.DASHBOARD.list",
        type: "item",
        icon: "circle",
        url: "settings/avatars",
      },
      {
        id: "avatars-add",
        title: "Add",
        translate: "MENU.DASHBOARD.add",
        type: "item",
        icon: "circle",
        url: "settings/add-avatar",
      },
    ],
  },
  {
    id: "avatars",
    title: "Avatars",
    translate:  "MENU.DASHBOARD.companies",
    type: "collapsible",
    icon: "image",
    children: [
      {
        id: "avatars-list",
        title: "List",
        translate: "MENU.DASHBOARD.list",
        type: "item",
        icon: "circle",
        url: "settings/avatars",
      },
      {
        id: "avatars-add",
        title: "Add",
        translate: "MENU.DASHBOARD.add",
        type: "item",
        icon: "circle",
        url: "settings/add-avatar",
      },
    ],
  },
  {
    id: "avatars",
    title: "Avatars",
    translate:  "MENU.DASHBOARD.consulting",
    type: "collapsible",
    icon: "image",
    children: [
      {
        id: "avatars-list",
        title: "List",
        translate: "MENU.DASHBOARD.list",
        type: "item",
        icon: "circle",
        url: "settings/avatars",
      },
      {
        id: "avatars-add",
        title: "Add",
        translate: "MENU.DASHBOARD.add",
        type: "item",
        icon: "circle",
        url: "settings/add-avatar",
      },
    ],
  },
  {
    id: "avatars",
    title: "Avatars",
    translate:  "MENU.DASHBOARD.categories",
    type: "collapsible",
    icon: "image",
    children: [
      {
        id: "avatars-list",
        title: "List",
        translate: "MENU.DASHBOARD.list",
        type: "item",
        icon: "circle",
        url: "settings/avatars",
      },
      {
        id: "avatars-add",
        title: "Add",
        translate: "MENU.DASHBOARD.add",
        type: "item",
        icon: "circle",
        url: "settings/add-avatar",
      },
    ],
  },
  {
    id: "avatars",
    title: "Avatars",
    translate:  "MENU.DASHBOARD.services",
    type: "collapsible",
    icon: "image",
    children: [
      {
        id: "avatars-list",
        title: "List",
        translate: "MENU.DASHBOARD.list",
        type: "item",
        icon: "circle",
        url: "settings/avatars",
      },
      {
        id: "avatars-add",
        title: "Add",
        translate: "MENU.DASHBOARD.add",
        type: "item",
        icon: "circle",
        url: "settings/add-avatar",
      },
    ],
  },
  {
    id: "avatars",
    title: "Avatars",
    translate:  "MENU.DASHBOARD.tags",
    type: "collapsible",
    icon: "image",
    children: [
      {
        id: "avatars-list",
        title: "List",
        translate: "MENU.DASHBOARD.list",
        type: "item",
        icon: "circle",
        url: "settings/avatars",
      },
      {
        id: "avatars-add",
        title: "Add",
        translate: "MENU.DASHBOARD.add",
        type: "item",
        icon: "circle",
        url: "settings/add-avatar",
      },
    ],
  },
  {
    id: "avatars",
    title: "Avatars",
    translate:  "MENU.DASHBOARD.articles",
    type: "collapsible",
    icon: "image",
    children: [
      {
        id: "avatars-list",
        title: "List",
        translate: "MENU.DASHBOARD.list",
        type: "item",
        icon: "circle",
        url: "settings/avatars",
      },
      {
        id: "avatars-add",
        title: "Add",
        translate: "MENU.DASHBOARD.add",
        type: "item",
        icon: "circle",
        url: "settings/add-avatar",
      },
    ],
  },
  {
    id: "avatars",
    title: "Avatars",
    translate: "MENU.DASHBOARD.offers",
    type: "collapsible",
    icon: "image",
    children: [
      {
        id: "avatars-list",
        title: "List",
        translate: "MENU.DASHBOARD.list",
        type: "item",
        icon: "circle",
        url: "settings/avatars",
      },
      {
        id: "avatars-add",
        title: "Add",
        translate: "MENU.DASHBOARD.add",
        type: "item",
        icon: "circle",
        url: "settings/add-avatar",
      },
    ],
  },
  {
    id: "avatars",
    title: "Avatars",
    translate:  "MENU.DASHBOARD.plantcards",
    type: "collapsible",
    icon: "image",
    children: [
      {
        id: "avatars-list",
        title: "List",
        translate: "MENU.DASHBOARD.list",
        type: "item",
        icon: "circle",
        url: "settings/avatars",
      },
      {
        id: "avatars-add",
        title: "Add",
        translate: "MENU.DASHBOARD.add",
        type: "item",
        icon: "circle",
        url: "settings/add-avatar",
      },
    ],
  },
 


    
]
