import { CoreMenu } from '@core/types'

export const menu: CoreMenu[] = [

  {
    id: "avatars",
    title: "Users",
    translate: "MENU.DASHBOARD.users",
    type: "collapsible",
    icon: "users",
    children: [
      {
        id: "avatars-list",
        title: "List",
        translate: "MENU.DASHBOARD.list",
        type: "item",
        icon: "circle",
        url: "settings/avatars",
      },
      {
        id: "avatars-add",
        title: "Add",
        translate: "MENU.DASHBOARD.add",
        type: "item",
        icon: "circle",
        url: "settings/add-avatar",
      },
    ],
  },
  {
    id: "avatars",
    title: "Ads",
    translate:  "MENU.DASHBOARD.ads",
    type: "collapsible" ,
    icon: "image", 
    children: [
      {
        id: "avatars-list",
        title: "List",
        translate: "MENU.DASHBOARD.list",
        type: "item",
        icon: "circle",
        url: "ads",
      },
      {
        id: "avatars-add",
        title: "Add",
        translate: "MENU.DASHBOARD.add",
        type: "item",
        icon: "circle",
        url: "add-ads",
      },
    ],
  },
  {
    id: "avatars",
    title: "Counselors",
    translate:  "MENU.DASHBOARD.counselors",
    type: "collapsible",
    icon: "package",
    children: [
      {
        id: "avatars-list",
        title: "List",
        translate: "Stores",
        type: "item",
        icon: "circle",
        url: "counselors",
      },
      {
        id: "avatars-add",
        title: "Add",
        translate: "MENU.DASHBOARD.add",
        type: "item",
        icon: "circle",
        url: "add-counselors",
      },
    ],
  },
  {
    id: "avatars",
    title: "Stores Offers",
    translate:  "MENU.DASHBOARD.stores_offers",
    type: "collapsible",
    icon: "dollar-sign",
    children: [
      {
        id: "avatars-list",
        title: "List",
        translate: "Vouchers",
        type: "item",
        icon: "circle",
        url: "StoresOffers-Vouchers",
      },
      {
        id: "avatars-add",
        title: "Add",
        translate: "MENU.DASHBOARD.add",
        type: "item",
        icon: "circle",
        url: "StoresOffers-add",
      },
    ],
  },
  {
    id: "avatars",
    title: "Cancelation Reason",
    translate:  "MENU.DASHBOARD.cancelation_reason",
    type: "collapsible",
    icon: "tablet",
    children: [
      {
        id: "avatars-list",
        title: "List",
        translate: "MENU.DASHBOARD.list",
        type: "item",
        icon: "circle",
        url: "CancelationReasons",
      },
      {
        id: "avatars-add",
        title: "Add",
        translate: "MENU.DASHBOARD.add",
        type: "item",
        icon: "circle",
        url: "CancelationReasons-add",
      },
    ],
  },
  {
    id: "avatars",
    title: "Companies",
    translate:  "MENU.DASHBOARD.companies",
    type: "collapsible",
    icon: "hexagon",
    children: [
      {
        id: "avatars-list",
        title: "List",
        translate: "MENU.DASHBOARD.list",
        type: "item",
        icon: "circle",
        url: "Companies",
      },
      {
        id: "avatars-add",
        title: "Add",
        translate: "MENU.DASHBOARD.add",
        type: "item",
        icon: "circle",
        url: "Companies-add",
      },
    ],
  },
  {
    id: "avatars",
    title: "Consulting",
    translate:  "MENU.DASHBOARD.consulting",
    type: "collapsible",
    icon: "credit-card",
    children: [
      {
        id: "avatars-list",
        title: "List",
        translate: "MENU.DASHBOARD.list",
        type: "item",
        icon: "circle",
        url: "Consulting",
      },
      {
        id: "avatars-add",
        title: "Add",
        translate: "MENU.DASHBOARD.add",
        type: "item",
        icon: "circle",
        url: "Consulting-add",
      },
    ],
  },
  {
    id: "avatars",
    title: "Categories",
    translate:  "MENU.DASHBOARD.categories",
    type: "collapsible",
    icon: "percent",
    children: [
      {
        id: "avatars-list",
        title: "List",
        translate: "MENU.DASHBOARD.list",
        type: "item",
        icon: "circle",
        url: "Categories",
      },
      {
        id: "avatars-add",
        title: "Add",
        translate: "MENU.DASHBOARD.add",
        type: "item",
        icon: "circle",
        url: "Categories-add",
      },
    ],
  },
  {
    id: "avatars",
    title: "Services",
    translate:  "MENU.DASHBOARD.services",
    type: "collapsible",
    icon: "map-pin",
    children: [
      {
        id: "avatars-list",
        title: "List",
        translate: "MENU.DASHBOARD.list",
        type: "item",
        icon: "circle",
        url: "Services",
      },
      {
        id: "avatars-add",
        title: "Add",
        translate: "MENU.DASHBOARD.add",
        type: "item",
        icon: "circle",
        url: "Services-add",
      },
    ],
  },
  {
    id: "avatars",
    title: "Tags",
    translate:  "MENU.DASHBOARD.tags",
    type: "collapsible",
    icon: "video",
    children: [
      {
        id: "avatars-list",
        title: "List",
        translate: "MENU.DASHBOARD.list",
        type: "item",
        icon: "circle",
        url: "Tags",
      },
      {
        id: "avatars-add",
        title: "Add",
        translate: "MENU.DASHBOARD.add",
        type: "item",
        icon: "circle",
        url: "Tags-add",
      },
    ],
  },
  {
    id: "avatars",
    title: "Articles",
    translate:  "MENU.DASHBOARD.articles",
    type: "collapsible",
    icon: "upload",
    children: [
      {
        id: "avatars-list",
        title: "List",
        translate: "MENU.DASHBOARD.list",
        type: "item",
        icon: "circle",
        url: "Articles",
      },
      {
        id: "avatars-add",
        title: "Add",
        translate: "MENU.DASHBOARD.add",
        type: "item",
        icon: "circle",
        url: "Articles-add",
      },
    ],
  },
  {
    id: "avatars",
    title: "Offers",
    translate: "MENU.DASHBOARD.offers",
    type: "collapsible",
    icon: "settings",
    children: [
      {
        id: "avatars-list",
        title: "List",
        translate: "MENU.DASHBOARD.list",
        type: "item",
        icon: "circle",
        url: "Offers",
      },
      {
        id: "avatars-add",
        title: "Add",
        translate: "MENU.DASHBOARD.add",
        type: "item",
        icon: "circle",
        url: "Offers-add",
      },
    ],
  },
  {
    id: "avatars",
    title: "Plant Cards",
    translate:  "MENU.DASHBOARD.plantcards",
    type: "collapsible",
    icon: "flag",
    children: [
      {
        id: "avatars-list",
        title: "List",
        translate: "MENU.DASHBOARD.list",
        type: "item",
        icon: "circle",
        url: "settings/avatars",
      },
      {
        id: "avatars-add",
        title: "Add",
        translate: "MENU.DASHBOARD.add",
        type: "item",
        icon: "circle",
        url: "settings/add-avatar",
      },
    ],
  },
 


    
]
